feat: slide da home.
tech-pro-bem/saude-da-rua-frontend pull request #68
Opened 2022-09-04 13:03 UTC by Antonio-Sitoe

adicionada o slide da home, parte responsiva com a biblioteca splide

2022-09-06 03:25 UTC, lucas-lm commented
Ótimo trabalho @Antonio-Sitoe !

@aferanda, @snowslaura , @X-SpeedBlack-X , pessoal, essa é uma boa oportunidade pra vocês fazerem um review no código do Antonio

2022-09-06 17:49 UTC, snowslaura reviewed
Antonio, excelente! Gostei mt do jeito que vc fez, vou utilizar sua hook para fazer o meu.
Uma única sugestão que tenho seria alterar o nome dos componentes para ficar mais semântico:
Slide> SlideMobile
SliderData> SlideDesktop

2022-09-06 21:17 UTC, Antonio-Sitoe commented
> Antonio, excelente! Gostei mt do jeito que vc fez, vou utilizar sua hook para fazer o meu. Uma única sugestão que tenho seria alterar o nome dos componentes para ficar mais semântico: Slide> SlideMobile SliderData> SlideDesktop

E para ja.

2022-09-07 17:34 UTC, lucas-lm commented on src/Hooks/useMedia.js
> +  return match;
Ótimo domínio do `useEffect` com a função de clean-up no final!

Esse hook vai ser muito útil para todo projeto e pode ser muito bem reaproveitado. Parabéns Antonio!

@tech-pro-bem/voluntarios-front, vejam como vocês podem se beneficiar desse hook.

2022-09-07 18:15 UTC, lucas-lm requested changes
@Antonio-Sitoe , tem algumas mudanças que eu enderecei no código pra você e também notei que tem um arquivo do `yarn`. Estamos usando apenas o `npm` como gerenciador de pacotes para o projeto, então não recomendaria a utilização do `yarn`. Além disso, também usamos uma versão específica do `node.js` e por isso temos essa configuração com o `nvm`, para evitar quebras de compatibilidade entre os ambientes de devenvolvimento locais de cada membro da equipe.

2022-09-07 18:15 UTC, lucas-lm commented on src/pages/Home/containers/OurActions/Mobile/style.js
> +  @media (min-width: 40rem) {
As unidades de medidas para media queries fazem mais sentido não serem relativas, porque você quer que a página seja responsiva de acordo com um tamanho fixo de tela e não que varie de acordo com uma medida definida no elemento `:root` da página

2022-09-10 21:01 UTC, Antonio-Sitoe commented on src/Hooks/useMedia.js
> +  return match;
valeu Lucas

2022-09-10 21:02 UTC, Antonio-Sitoe commented
> @Antonio-Sitoe , tem algumas mudanças que eu enderecei no código pra você e também notei que tem um arquivo do `yarn`. Estamos usando apenas o `npm` como gerenciador de pacotes para o projeto, então não recomendaria a utilização do `yarn`. Além disso, também usamos uma versão específica do `node.js` e por isso temos essa configuração com o `nvm`, para evitar quebras de compatibilidade entre os ambientes de devenvolvimento locais de cada membro da equipe.

entao sobre o yarn ja resolve, e estou a usar a vercao 14.20.0 do nodejs

2022-09-10 21:03 UTC, Antonio-Sitoe commented on src/pages/Home/Home.jsx
> +  SlideMobile,
resolvido

2022-09-10 21:07 UTC, Antonio-Sitoe commented on src/pages/Home/Home.jsx
> +import useMedia from '../../Hooks/useMedia';
ja resolvido

2022-09-10 21:08 UTC, Antonio-Sitoe commented on src/Hooks/useMedia.js
> +export default useMedia;
check

2022-09-10 21:11 UTC, Antonio-Sitoe commented on src/pages/Home/containers/OurActions/Mobile/SlideMobile.js
> +import { Highlight } from '@components';
Nao fui eu quem fez, mas o codigo esta no arquivo **config-overrides.js**

2022-09-10 21:34 UTC, Antonio-Sitoe commented on src/pages/Home/containers/OurActions/Mobile/SlideMobile.js
> +    });
sim, tens toda razao, o problema ai esta na renderizacao desses buttons, eles nao estao na pagina e so aparecem no quando o js for carregado, entao nao tem como colocalos de modo estatico, a unica maneira que encontrei foi essa de colocar no useEffect.

2022-09-10 21:36 UTC, Antonio-Sitoe commented on src/pages/Home/containers/OurActions/Mobile/style.js
> +  @media (min-width: 40rem) {
check

2022-09-11 03:52 UTC, Antonio-Sitoe commented on src/pages/Home/containers/OurActions/Mobile/SlideMobile.js
> +    });
Sim, Lucas, você tem toda a razão, normalmente eu uso useRef() para acessar elementos na Dom.

Contudo, neste caso é diferente, pois a lista de navegação é  [ gerada dinamicamente pela lib](https://splidejs.com/guides/pagination/).

Ate o exemplo da documentacao esta assim:

`
const splide = new Splide( '.splide' );


splide.on( 'pagination:mounted', function ( data ) {
  // You can add your class to the UL element
  data.list.classList.add( 'splide__pagination--custom' );


  // `items` contains all dot items
  data.items.forEach( function ( item ) {
    item.button.textContent = String( item.page + 1 );
  } );
} );


splide.mount();
`

Em todo caso parece ate gambiarra, mas eu tentei de todas as maneiras que pude, então a única conclusão que consegue foi de isolar essa lógica, pois quando eu coloco os elementos estaticamente no componente, ao invés de serem 3 eles aumentam para 6 e causam conflitos uns com os outros, pois eles são gerados segundo cada elemento do slide.

2022-09-18 13:48 UTC, lucas-lm commented on src/pages/Home/containers/OurActions/Mobile/SlideMobile.js
> +    });
Reparei que você resolveu mudar a abordagem e seguir com outra biblioteca. Ficou bom Antonio :)

2022-09-18 13:53 UTC, lucas-lm requested changes
@Antonio-Sitoe, precisamos de uma última alteração. Apagar um import que restou da lib splidejs que foi desinstalada.

2022-09-18 13:53 UTC, lucas-lm commented on src/App.js
> +import '@splidejs/react-splide/css/core';
@Antonio-Sitoe, como a biblioteca splidejs foi desinstalada e estamos usando a keen-slider no seu lugar, devemos apagar esse import. Está dando erro na compilação.
```suggestion
```

Feito essa alteração deve tudo funcionar bem e estaremos prontos pra fazer o merge :)

2022-09-22 19:22 UTC, X-SpeedBlack-X reviewed
Gostei demais, Antônio. Parabéns!

2022-09-23 00:19 UTC, lucas-lm approved these changes

2022-09-23 00:43 UTC, merged