[BSDR 122] Home: Onde estamos
tech-pro-bem/saude-da-rua-frontend pull request #69
Opened 2022-09-09 16:40 UTC by aferanda

2022-09-13 12:20 UTC, Antonio-Sitoe reviewed
Esta tudo bem.

2022-09-14 18:51 UTC, snowslaura reviewed
Okay!!

2022-09-18 16:48 UTC, lucas-lm requested changes
@aferanda, deixei algumas alterações para você fazer. Principalmente no código dos componentes compartilhados.

2022-09-18 16:48 UTC, lucas-lm commented on src/components/Highlight/Highlight.jsx
> +    text-decoration: none !important;
@aferanda, porque definir `text-decoration: none` aqui? Talvez fizesse mais sentido adicionar essa estilização em um nível mais alto (componente local da página) ou talvez adicionar uma variante do componente
```suggestion
```

2022-09-18 16:48 UTC, lucas-lm commented on src/components/OutlinedImage/OutlinedImage.style.js
> +    }
Essa estilização não deveria ser feita aqui, porque vai forçar que o componente se comporte com esses números fixados por todas as páginas.  Esse componente será utilizado em vários lugares do site, por isso ele precisa ser bem genérico para poder ser reaproveitado em qualquer situação e seu código deve ser estável para não causar nenhuma quebra inesperada.

Eu tenho algumas sugestões para tornar o componente responsivo:
1. Adicionar propriedades para media queries. Ex:
```jsx
@media screen and (max-width: ${ ({ responsive }) => responsive.maxWidth}) {
    border-radius: ${ ( {responsive} )=> responsive.borderRadius || defaultBorderRadius };
    left: ${ ( {responsive} )=> responsive.left || defaultLeft };
    ...
}
```
Dessa forma o componente continua flexível, adaptável e sem causar nenhum impacto aos seus clientes (clientes nesse caso são as páginas que estão consumindo ele)

2. Usar o hook do @Antonio-Sitoe (`useMedia`) para alterar as propriedades do componente dinamicamente de acordo com a media query:
```jsx
const query = "..."
const mobile = useMedia(query)
...
<OutlinedImage borderWidth="3px /*(props comuns)*/" {mobile ? ...mobileProps : ...desktopProps /* props específicas*/ } />
```

3. Não alterar o código do componente em si e usar unidade de medidas relativas ao consumir o componente:
```jsx
<OutlinedImage borderRadius="2em" borderLeft="1em" ...otherProps>
```

4. Criar um componente local a partir do componente `OutlinedImage` e aplicar as estilizações:
```jsx
import styled from 'styled-components'
import { OutlinedImage } from '@components'

export const StyledOutlinedImage = styled(OutlinedImage)`
...css /* Código de estilização específica aqui */
`
```

Também não é recomendável usar o `!important` a menos que seja estritamente necessário

2022-09-18 16:48 UTC, lucas-lm commented on src/components/OutlinedImage/OutlinedImage.style.js
> +    max-width: 98%;
A mesma ideia do comentário anterior também se aplica aqui

2022-09-26 22:44 UTC, guiRepo approved these changes
LGTM

2022-09-29 00:06 UTC, aferanda commented on src/components/Highlight/Highlight.jsx
> +    text-decoration: none !important;
@lucas-lm, linha removida.

2022-09-29 00:06 UTC, aferanda commented on src/components/OutlinedImage/OutlinedImage.style.js
> +    }
@lucas-lm, segui a primeira sugestão. Obrigada!

2022-09-30 04:18 UTC, lucas-lm approved these changes

2022-09-30 12:04 UTC, merged