BSDR 109
tech-pro-bem/saude-da-rua-frontend pull request #72
Opened 2022-09-22 19:23 UTC by X-SpeedBlack-X

### [BSDR 109] - Menu Lateral

2022-09-23 12:18 UTC, guiRepo requested changes
Isaque, o seu código deu um erro no build no netlify, algo relacionado ao componente Header que você excluiu, ele estava sendo importado no 'src/components/index.js', quando voce criou o outro você alterou ele importação dele tambem?

2022-09-27 15:58 UTC, snowslaura reviewed
@X-SpeedBlack-X  Isaque, legal essa função Scroll.
Uma coisa que tenho feito e não necessariamente vc deva fazer, só uma sugestão, é separar os elementos que vc criou para Mobile em uma pasta, e os de Desktop em outra pasta.
Dessa forma o arquivo não fica muito grande com muitas informações. 
Ex:
src/components/Footer/Mobile/os componentes
src/components/Footer/Desktop/os componentes

2022-09-28 12:32 UTC, X-SpeedBlack-X commented
> @X-SpeedBlack-X Isaque, legal essa função Scroll. Uma coisa que tenho feito e não necessariamente vc deva fazer, só uma sugestão, é separar os elementos que vc criou para Mobile em uma pasta, e os de Desktop em outra pasta. Dessa forma o arquivo não fica muito grande com muitas informações. Ex: src/components/Footer/Mobile/os componentes src/components/Footer/Desktop/os componentes



> @snowslaura Obrigado, Laura. Vou considerar e fazer a refatoração!!

2022-09-28 13:15 UTC, guiRepo approved these changes
LGTM

2022-09-28 13:16 UTC, merged