Bsdr 125 como doar
tech-pro-bem/saude-da-rua-frontend pull request #75
Opened 2022-09-27 12:18 UTC by Antonio-Sitoe

2022-10-05 22:56 UTC, guiRepo commented on src/pages/Donation/containers/HelpNow/Mobile/HelpNowMobile.jsx
> +      <div style={{ padding: '0 15px' }}>
A caráter de padronização, transforme essa div em um styled component.

2022-10-05 22:57 UTC, guiRepo commented on src/pages/Donation/containers/HelpNow/Mobile/containers/HelpNowHero.jsx
> +const HelpNowHeroContainer = styled.section`
crie um arquivo styles.js para colocar la os compomentes estilizados que voce esta utilizando aqui, alem de transformar os demais elementos em styled component também.

2022-10-05 23:08 UTC, guiRepo commented on src/pages/Donation/containers/HelpNow/Mobile/containers/HowHelpContent.jsx
> +const HowHelpContent = ({ HelpInformation }) => {
Pela quantidade de elementos contidos no arquivo, vale a pena voce aplicar o styled components nele pra ficar de acordo com o padrão do projeto

2022-10-05 23:09 UTC, guiRepo requested changes
@Antonio-Sitoe , deixei algumas considerações no seu codigo.

2022-10-09 16:48 UTC, Antonio-Sitoe commented on src/pages/Donation/containers/HelpNow/Mobile/containers/HelpNowHero.jsx
> +const HelpNowHeroContainer = styled.section`
ja fiz

2022-10-09 16:51 UTC, Antonio-Sitoe commented on src/pages/Donation/containers/HelpNow/Mobile/HelpNowMobile.jsx
> +      <div style={{ padding: '0 15px' }}>
resolvido

2022-10-09 16:51 UTC, Antonio-Sitoe commented on src/pages/Donation/containers/HelpNow/Mobile/containers/HowHelpContent.jsx
> +const HowHelpContent = ({ HelpInformation }) => {
resolvido

2022-10-13 20:42 UTC, guiRepo approved these changes

2022-10-13 20:42 UTC, merged